services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    command:
      [
        "postgres",
        "-c",
        "log_statement=all",
        "-c",
        "wal_level=logical",
        "-c",
        "max_wal_senders=10",
        "-c",
        "max_replication_slots=10",
      ]
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

  logflare:
    image: supabase/logflare:latest
    restart: always
    depends_on:
      - postgres
    environment:
      DB_DATABASE: dev
      DB_HOSTNAME: postgres
      DB_PORT: 5432
      DB_PASSWORD: dev
      DB_USERNAME: dev
      LOGFLARE_SINGLE_TENANT: true
      LOGFLARE_API_KEY: dev
      POSTGRES_BACKEND_URL: postgresql://dev:dev@postgres:5432/dev
      POSTGRES_BACKEND_SCHEMA: dev
    hostname: 127.0.0.1
    ports:
      - "4000:4000"

volumes:
  data:
