services:
  typesense:
    container_name: typesense
    image: typesense/typesense:27.0
    restart: always
    environment:
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_API_KEY: dev
      TYPESENSE_ENABLE_CORS: true
    ports:
      - 8108:8108
    volumes:
      - data:/data

volumes:
  data:
