services:
  zincsearch:
    container_name: zincsearch
    image: public.ecr.aws/zinclabs/zincsearch:latest
    environment:
      ZINC_FIRST_ADMIN_USER: dev
      ZINC_FIRST_ADMIN_PASSWORD: dev
      ZINC_DATA_PATH: /data
    ports:
      - 4080:4080
    volumes:
      - data:/data

volumes:
  data:
