services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    command:
      [
        "postgres",
        "-c",
        "log_statement=all",
        "-c",
        "wal_level=logical",
        "-c",
        "max_wal_senders=10",
        "-c",
        "max_replication_slots=10",
      ]
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

  temporal:
    container_name: temporal
    image: temporalio/auto-setup:latest
    restart: always
    depends_on:
      - postgresql
    environment:
      DB: postgres
      DB_PORT: 5432
      POSTGRES_USER: dev
      POSTGRES_PWD: dev
      POSTGRES_SEEDS: postgresql
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development-sql.yaml
    networks:
      - temporal-network
    ports:
      - 7233:7233

  temporal_admin_tools:
    container_name: temporal_admin_tools
    image: temporalio/admin-tools:latest
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - temporal
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CLI_ADDRESS: temporal:7233
    networks:
      - temporal-network

  temporal_ui:
    container_name: temporal_ui
    image: temporalio/ui:latest
    restart: always
    depends_on:
      - temporal
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CORS_ORIGINS: http://localhost:3000
    networks:
      - temporal-network
    ports:
      - 8080:8080

networks:
  temporal-network:
    driver: bridge
    name: temporal-network

volumes:
  data:
